// AUTO-GENERATED baseline of `renderMarkdown` output, captured to guard the
// tail refactor (T2). Proven byte-identical before and after the refactor.
export const SNAPSHOT_MARKDOWN = "# Title\n\nIntro paragraph with **bold**, _italic_, ~~strike~~ and `inline`.\n\n## Section\n## Section\n\n- one\n- two\n\n1. first\n2. second\n\n> a quote\n\n[a link](https://example.com)\n\n---\n\n```ts\nconst x: number = 1\nfunction greet(name: string) {\n  return `hi ${name}`\n}\n```\n\nTrailing text.\n"

export const SNAPSHOT_HTML = "<h1 id=\"title\">Title</h1>\n<p>Intro paragraph with <strong>bold</strong>, <em>italic</em>, ~~strike~~ and <code>inline</code>.</p>\n<h2 id=\"section\">Section</h2>\n<h2 id=\"section-2\">Section</h2>\n<ul>\n<li>one</li>\n<li>two</li>\n</ul>\n<ol>\n<li>first</li>\n<li>second</li>\n</ol>\n<blockquote>\n<p>a quote</p>\n</blockquote>\n<p><a href=\"https://example.com\">a link</a></p>\n<hr>\n<figure data-rehype-pretty-code-figure=\"\"><pre tabindex=\"0\" data-language=\"ts\" data-theme=\"vesper\"><code data-language=\"ts\" data-theme=\"vesper\" style=\"display: grid;\"><span data-line=\"\"><span style=\"color:#A0A0A0\">const</span><span style=\"color:#FFF\"> x</span><span style=\"color:#A0A0A0\">:</span><span style=\"color:#FFC799\"> number</span><span style=\"color:#A0A0A0\"> =</span><span style=\"color:#FFC799\"> 1</span></span>\n<span data-line=\"\"><span style=\"color:#A0A0A0\">function</span><span style=\"color:#FFC799\"> greet</span><span style=\"color:#FFF\">(name</span><span style=\"color:#A0A0A0\">:</span><span style=\"color:#FFC799\"> string</span><span style=\"color:#FFF\">) {</span></span>\n<span data-line=\"\"><span style=\"color:#A0A0A0\">  return</span><span style=\"color:#99FFE4\"> `hi ${</span><span style=\"color:#FFF\">name</span><span style=\"color:#99FFE4\">}`</span></span>\n<span data-line=\"\"><span style=\"color:#FFF\">}</span></span></code></pre></figure>\n<p>Trailing text.</p>"

export const SNAPSHOT_HEADINGS = [{"id":"title","text":"Title","level":1},{"id":"section","text":"Section","level":2},{"id":"section-2","text":"Section","level":2}] as const

export const SNAPSHOT_READ_TIME = 1
